language: php
sudo: false
addons:
  apt:
    packages:
      - libopenblas-dev
      - libopenblas-base
dist: trusty
php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1


cache:
    apt: true

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction --ignore-platform-reqs

before_script:
    - ccache --version
    - ccache --zero-stats
    - git clone https://github.com/phpsci/phpsci-ext.git
    - cd phpsci-ext
    - ./travis/compile.sh
    - cd ..
    - phpenv config-add travis/build.ini

script:
    - cd $TRAVIS_BUILD_DIR
    - export USE_ZEND_ALLOC=0
    - vendor/bin/phpunit
